export const availableProductsListData = [
  {
    pid: "p1",
    title: "SAGE TERM LIFE INSURANCE",
    term: "10-Year Term",
    price: "60",
    feature1: "Lowest yearly premium",
    feature2: "Rates are guaranteed never to increase over a 10-year period",
  },
  {
    pid: "p2",
    title: "SAGE TERM LIFE INSURANCE",
    term: "10-Year Term",
    price: "100",
    feature1: "Lowest yearly premium",
    feature2: "Rates are guaranteed never to increase over a 10-year period",
  },
  {
    pid: "p3",
    title: "SAGE TERM LIFE INSURANCE",
    term: "10-Year Term",
    price: "150",
    feature1: "Lowest yearly premium",
    feature2: "Rates are guaranteed never to increase over a 10-year period",
  },
  {
    pid: "p4",
    title: "SAGE TERM LIFE INSURANCE",
    term: "10-Year Term",
    price: "250",
    feature1: "Lowest yearly premium",
    feature2: "Rates are guaranteed never to increase over a 10-year period",
  },
  {
    pid: "p1",
    title: "SAGE TERM LIFE INSURANCE",
    term: "10-Year Term",
    price: "60",
    feature1: "Lowest yearly premium",
    feature2: "Rates are guaranteed never to increase over a 10-year period",
  },
  {
    pid: "p2",
    title: "SAGE TERM LIFE INSURANCE",
    term: "10-Year Term",
    price: "100",
    feature1: "Lowest yearly premium",
    feature2: "Rates are guaranteed never to increase over a 10-year period",
  },
  {
    pid: "p3",
    title: "SAGE TERM LIFE INSURANCE",
    term: "10-Year Term",
    price: "150",
    feature1: "Lowest yearly premium",
    feature2: "Rates are guaranteed never to increase over a 10-year period",
  },
  {
    pid: "p4",
    title: "SAGE TERM LIFE INSURANCE",
    term: "10-Year Term",
    price: "250",
    feature1: "Lowest yearly premium",
    feature2: "Rates are guaranteed never to increase over a 10-year period",
  },
  {
    pid: "p1",
    title: "SAGE TERM LIFE INSURANCE",
    term: "10-Year Term",
    price: "60",
    feature1: "Lowest yearly premium",
    feature2: "Rates are guaranteed never to increase over a 10-year period",
  },
  {
    pid: "p2",
    title: "SAGE TERM LIFE INSURANCE",
    term: "10-Year Term",
    price: "100",
    feature1: "Lowest yearly premium",
    feature2: "Rates are guaranteed never to increase over a 10-year period",
  },
  {
    pid: "p3",
    title: "SAGE TERM LIFE INSURANCE",
    term: "10-Year Term",
    price: "150",
    feature1: "Lowest yearly premium",
    feature2: "Rates are guaranteed never to increase over a 10-year period",
  },
  {
    pid: "p4",
    title: "SAGE TERM LIFE INSURANCE",
    term: "10-Year Term",
    price: "250",
    feature1: "Lowest yearly premium",
    feature2: "Rates are guaranteed never to increase over a 10-year period",
  },
];
